### ISSUE TITLE
AttributeError when trying to save report

### ISSUE THREAD

**Issue by lrumanes** [evidentlyai/evidently#36] opened 2021-07-16 22:52 UTC
When saving a report using 

data_drift_report.save("/dbfs/FileStore/drift/drift_report.html")

I get 

AttributeError: 'DataDriftTableWidget' object has no attribute 'wi'

caused by 

/databricks/python/lib/python3.8/site-packages/evidently/widgets/data_drift_table_widget.py in get_info(self)
     25 
     26     def get_info(self) -> BaseWidgetInfo:
---> 27         if self.wi:
     28             return self.wi
     29         raise ValueError("no widget info provided")

I'm using azure databricks, and can save the json profile, and get the same error if I use data_drift_report.show(), though I never installed nbextension.   

I can save the iris report, and am using numerical and categorical feature mappings.

**Comment by Chien10** [comment] 2021-07-17 09:04
I had the same issue when I forgot to include the `prediction` key in the `column_mapping` dictionary.

**Comment by elenasamuylova** [comment] 2021-07-19 11:26
@Chien10 thanks for helping out!

**Comment by lrumanes** [comment] 2021-07-19 21:57
Including prediction didn't help, and I was only running a data drift report.

**Comment by elenasamuylova** [comment] 2021-07-23 12:29
Hi @lrumanes, could you share 1) a snippet of how your pandas dataframe looks for reference and current datasets (e.g. a header and 1 line of data) 2) a line of code where you run the calculate function?

**Comment by lrumanes** [comment] 2021-07-28 23:17
This appears to have been caused by encoding the categorical data incorrectly.  Is there any way to pass a map of the original values of the data in so column values display in the graphs in admit_data_drift_report.save and admit_data_drift_report.show?

**Comment by emeli-dral** [comment] 2021-09-06 16:21
Hi @lrumanes, apologies for taking the time to get back to you here!

We tried a bunch of combinations but where unable to reproduce the error. Our best guess for now is that there is some error on the dataframe side or e.g. in column mapping.

Could you share the snippet of your code where you specify the column mapping and call the "calculate" command? If it is not sensitive, ideally with a preview of your dataframe (just 2-5 lines would do). You can also send it to email hello@evidentlyai.com or privately in our Discord channel https://discord.gg/xZjKRaNp8b

**Comment by emeli-dral** [comment] 2022-01-20 13:21
> This appears to have been caused by encoding the categorical data incorrectly. Is there any way to pass a map of the original values of the data in so column values display in the graphs in admit_data_drift_report.save and admit_data_drift_report.show?

yes, this is still an open issue. Unfortunately, at the moment there are no ways to pass a map for categorical data encoding. 
However, we already working on this issue in PR: https://github.com/evidentlyai/evidently/pull/113
Hopefully, this will be fixed soon enough and all Dashboards will work correctly with categorical data without encoding.

**Closed by emeli-dral** 2022-01-20 13:21 UTC
